### ISSUE TITLE
R&D: Gem caching

### ISSUE THREAD

**Issue by mcritchlow** [jhriv/spotlight-demo#12]
### Descriptive summary

If ansible master could cache the ruby gems, it might significantly improve performance. Similar to how Solr/Java are cached.

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by jhriv** [comment]
https://github.com/bundler/gemstash

This may be useful - either on the dev machine (but the guest would need a way to access it), inside the vagrant box (though this is less useful when destroying said box), or on another VM in our vSphere.
