### ISSUE TITLE
Reindex Status UI does not display correct status

### ISSUE THREAD

**Issue by VivianChu** [jhriv/spotlight-demo#22]
**ISSUE:**
- As admin, when I select re-index function, the status does not display correct status even the timestamp for these objects are updated correctly. 
![spotlight-reindex-problem](https://cloud.githubusercontent.com/assets/1864660/25054428/f0f7290a-2111-11e7-8aef-2faab8478a04.png)

**Comment by VivianChu** [comment]
@mcritchlow - I updated the spotlight gem in my local vagrant spotlight to fix this issue.  Attached is the screen shot.  However, this is a spotlight code bug.  We can't really deploy this code change.  We can either clone the repository, update it and our vagrant config file to use that version of spotlight, or we can report the bug so spotlight developer can fix it.  What do you think?  Thanks

![reindexallupdate](https://cloud.githubusercontent.com/assets/1864660/25359408/07b0ce22-28fa-11e7-8abe-0bed13646e03.png)

**Comment by mcritchlow** [comment]
@VivianChu - Great job 👍  I think if it's a reproducible bug that you can (and it seems like already have) fix in Spotlight, it would be worth:

- Filing an issue with Spotlight documenting the bug and how you fixed it
- Ask if they would like a PR with your proposed fixes to address the issue

It would be great to be able to help make Spotlight better if we can, and this seems like a good opportunity to do so while fixing a local need.
