### ISSUE TITLE
Search configuration error

### ISSUE THREAD

**Issue by gamontoya** [jhriv/spotlight-demo#3]
**ISSUE:**
- When in the admin Dashboard, clicking on _Search_ in **Configuration**, I get an InvalidRequest error.

![1](https://cloud.githubusercontent.com/assets/4314914/23924747/391fb94c-08c9-11e7-929c-be3c81999cd0.png)

**Comment by VivianChu** [comment]
@gamontoya  I got it working locally.  Attached is the screen shot.  I will let you know when the change get deployed.  Thanks
![search-configuration](https://cloud.githubusercontent.com/assets/1864660/24669760/7b955f36-1920-11e7-8eec-41296c47eb40.png)
