### ISSUE TITLE
Browse curation error

### ISSUE THREAD

**Issue by gamontoya** [jhriv/spotlight-demo#4]
**ISSUE:**
- When in the admin Dashboard, clicking on _Browse_ in **Curation**, I get an InvalidRequest error.

![2](https://cloud.githubusercontent.com/assets/4314914/23924826/8d337c30-08c9-11e7-9594-c85d5388004c.png)

**Comment by VivianChu** [comment]
@gamontoya I got it working locally. Attached is the screen shot. I will let you know when the change get deployed. Thanks
![browse-curation](https://cloud.githubusercontent.com/assets/1864660/24669797/97bc3d9c-1920-11e7-81fe-2333b9d1994e.png)
