### ISSUE TITLE
Cannot add item/object

### ISSUE THREAD

**Issue by gamontoya** [jhriv/spotlight-demo#6]
**ISSUE:**
- As admin, when I add an **item** (Curation, upload image, enter metadata, save), I receive an Object loaded successfully message, but I cannot see/retrieve the object in the UI.

![4](https://cloud.githubusercontent.com/assets/4314914/23924926/007712a6-08ca-11e7-9c3d-dbe4bcfc0a2c.png)

**Comment by VivianChu** [comment]
@gamontoya - The problem has been fixed locally.  Here's the screen shot.
![additem](https://cloud.githubusercontent.com/assets/1864660/24935145/e5b4dd06-1ed4-11e7-8cb2-e855bebe4af9.png)

**Comment by gamontoya** [comment]
@VivianChu :+1:
