### ISSUE TITLE
Error received when re-indexing

### ISSUE THREAD

**Issue by gamontoya** [jhriv/spotlight-demo#7]
**ISSUE:**
- As **admin**, when I select Re-index items, I receive the following error message: An error occured while reindexing. Contact your exhibits administrator for more information.

![5](https://cloud.githubusercontent.com/assets/4314914/23924955/28039574-08ca-11e7-9f69-fc739e74804a.png)

**Comment by VivianChu** [comment]
@gamontoya - The problem has been fixed locally. Here's the screen shot.
![spotlight-reindex](https://cloud.githubusercontent.com/assets/1864660/25054098/1c7a9c58-2110-11e7-8b3f-06017a5c7fc5.png)

**Comment by gamontoya** [comment]
:+1:
